version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dart

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python

  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - android
